name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: open-goal/mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "Orb Hunt"
      metadataDescription: "Precursor Orb Scavenger Hunt"
      metadataSupportedGames: "jak1,jak2"
      metadataAuthors: "barg"
      metadataTags: "speedrunning,challenge,gameplay-mod"
      metadataWebsiteUrl: "https://github.com/dallmeyer/OG-OrbHunt/blob/main/README.md"
      toolingRepo: "OpenGOAL-Mods/OG-Mod-Base"
      gameAssetsDir: "game/assets"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
